version: "3"
services:
    app:
        container_name: micro_lab
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
          - .:/app
          - ./node_modules:/app/node_modules
          - ../frontend/dist/micro-lab/:/app/public
        ports:
          - 3000:3000
            