openapi: 3.0.0
info:
    version: 1.0.0
    title: Vizsgaremek Szerver API Dokumentáció
    description: A Vizsgaremek végpontjainak részletes leírása és használata
servers:
    - url: http://localhost:3000
paths:
    /patient:
        get:
            description: Returns a list of patients
            security:
                - bearerAuth: []
            responses:
                '200':
                    description: Success
                    content:
                        aplication/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Patient'
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        Patient:
            type: object
            require:
                - name
                - taj
                - birth_date
                - mothers_name
            properties:
                name:
                    type: string
                taj:
                    type: number
                birth_date:
                    type: string
                mothers_name:
                    type: string